printJob:
  inEncoding:   iso-8859-1
  outEncoding:  iso-8859-1
  startCommand: ''
  endCommand:   ''
  filenameExtension:  'txt'

page:
  pageEnd:      ''
  lineEnd:      'windows'
  headerLine:   'COLUMN_NAMES'
  headerSeparator: ''
  pageHeight:   66
  pageWidth:    196
  topMargin:    1
  headerMargin: 0
  bottomMargin: 1
  leftMargin:   0
  rightMargin:  0
  columnSeparator: ' '
columns:
  - column:
      adif: 'QSO_DATE'
      header: 'DATE'
      length: 10
      format: 'YYYY-MM-dd'
      align:  left
  - column:
      adif: 'TIME_ON'
      header: 'TIME'
      length: 5
      format: 'HH:mm'
      align: left
  #  - column:
  #      adif: 'STATION_CALLSIGN'
  #      header: 'MY CALL'
  #      length: 10
  #      align: left
  - column:
      adif: 'CALL'
      header: 'THEIR CALL'
      length: 14
      align: left
  - column:
      adif: 'FREQ'
      header: 'FREQ'
      length: 8
      format: '%8.3f'
      align: right
  - column:
      adif: 'MODE'
      header: 'MODE'
      length: 4
      align: right
  - column:
      adif: 'RST_RCVD'
      header: 'RSR'
      length: 3
      align: right
  - column:
      adif: 'RST_SENT'
      header: 'RST'
      length: 3
      align: right
  - column:
      adif: 'MY_SOTA_REF'
      header: 'SOTA-TX'
      length: 10
  - column:
      adif: 'SOTA_REF'
      header: 'SOTA-RX'
      length: 10
  - column:
      adif: 'NAME'
      header: 'OPERATOR'
      length: 26
  - column:
      adif: 'COUNTRY'
      header: 'COUNTRY'
      length: 16
  - column:
      adif: 'GRIDSQUARE'
      header: 'MHL'
      length: 6
  - column:
      adif: 'DISTANCE'
      header: 'DIST'
      length: 5
      format: '%4.0f'
      align: right
  - column:
      adif: 'QTH'
      header: 'QTH'
      length: 31
  - column:
      adif: 'COMMENT'
      header: 'COMMENT'
      length: 30
