package uk.m0nom.adifweb.domain;

public enum HtmlParameterType {
    FILENAME,
    LATITUDE,
    LONGITUDE,
    LATLONG,
    SOTA_REF,
    WOTA_REF,
    HEMA_REF,
    POTA_REF,
    WWFF_REF,
    GRID,
    ENCODING,
    STATION_SUBLABEL,
    LOCAL_ACTIVATION_SITES,
    LOCAL_ACTIVATION_SITES_RADIUS,
    ANTENNA_TAKEOFF_ANGLE,
    CONTEST_RESULTS,
    SATELLITE_NAME,
    SATELLITE_MODE,
    SOTA_MICROWAVE_AWARD_COMMENT;
}
