on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Java 21 compile
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk

      - name: Compile the Project
        run: mvn -B compile --file pom.xml

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk

      - name: Build and test project
        run: mvn -Pprod -B verify spring-boot:repackage antrun:run@repackage

      - name: Version deployment archive
        run: mv -v target/adifweb.zip target/adifweb-${{ github.sha }}.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
            name: adifweb-${{ github.sha }}.zip
            path: target/adifweb-${{ github.sha }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy adifweb to AWS Elastic Beanstalk
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }} # These are the keys for AWS user github_actions
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Download ZIP
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v2
        with:
          name: adifweb-${{ github.sha }}.zip

      - name: Upload package to S3 bucket
        run: aws s3 cp adifweb-${{ github.sha }}.zip s3://adifweb-deploy/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name adifweb \
          --source-bundle S3Bucket="adifweb-deploy",S3Key="adifweb-${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Adifweb-env --version-label "ver-${{ github.sha }}"
